/**
 * Xylarc AI — Built-in Agent System Templates
 * Canonical enterprise agent specifications defined in §12 & §39 of CLAUDE.md.
 */

import { AgentSpecification } from '../types/agentTypes.js';

export const SYSTEM_AGENT_TEMPLATES: AgentSpecification[] = [
  {
    slug: 'business_orchestrator',
    name: 'Business Orchestrator Agent',
    description: 'High-level business orchestrator that decomposes complex requests, delegates to managers and specialists, and aggregates verified outcomes.',
    category: 'orchestrator',
    department: 'executive',
    autonomyLevel: 3,
    riskTier: 'MEDIUM',
    version: '1.0.0',
    isSystem: true,
    config: {
      systemPrompt: 'You are the Xylarc Business Orchestrator. You analyze strategic business objectives, decompose them into structured sub-tasks, delegate to specialized department agents, and synthesize verified business results.',
      tools: ['dispatch_agent_task', 'query_customer_360', 'evaluate_policy_rules', 'escalate_to_human'],
      dataAccessScope: ['customer_timeline', 'agent_registry', 'metrics_read', 'policy_read'],
      modelPolicy: {
        primaryModel: 'gemini-2.5-pro',
        fallbackModel: 'gemini-2.5-flash',
        temperature: 0.1,
        maxTokens: 8192,
      },
      escalationRules: {
        triggers: ['conflicting_specialist_results', 'unmet_policy_precondition', 'budget_exhausted'],
        escalationTarget: 'human',
        minConfidenceThreshold: 0.85,
      },
      limits: {
        maxConcurrentTasks: 25,
        maxCostPerExecutionUsd: 1.50,
        timeoutMs: 60000,
        maxDailyOutreachPerCustomer: 3,
      },
      verificationApproach: 'deterministic',
      owner: 'system',
    },
  },
  {
    slug: 'sales_lead_qualifier',
    name: 'Sales Lead Qualifier Agent',
    description: 'Engages inbound leads across WhatsApp and Web, scores intent, answers pre-sales questions, and qualifies prospects for sales operations.',
    category: 'specialist',
    department: 'sales',
    autonomyLevel: 2,
    riskTier: 'LOW',
    version: '1.0.0',
    isSystem: true,
    config: {
      systemPrompt: 'You are the Xylarc Sales Lead Qualifier. You evaluate lead fit, extract requirements, calculate BANT qualification scores, and prepare consultation recommendations.',
      tools: ['extract_lead_profile', 'score_lead_intent', 'whatsapp_send_template', 'schedule_meeting'],
      dataAccessScope: ['customer_profile', 'product_catalog', 'pricing_read'],
      modelPolicy: {
        primaryModel: 'gemini-2.5-flash',
        fallbackModel: 'gemini-2.5-pro',
        temperature: 0.2,
        maxTokens: 4096,
      },
      escalationRules: {
        triggers: ['enterprise_deal_detected', 'pricing_negotiation_requested', 'negative_sentiment'],
        escalationTarget: 'human',
        minConfidenceThreshold: 0.80,
      },
      limits: {
        maxConcurrentTasks: 15,
        maxCostPerExecutionUsd: 0.30,
        timeoutMs: 30000,
        maxDailyOutreachPerCustomer: 3,
      },
      verificationApproach: 'deterministic',
      owner: 'system',
    },
  },
  {
    slug: 'appointment_booking_specialist',
    name: 'Appointment & Booking Specialist',
    description: 'Manages calendar availability, books customer appointments, handles rescheduling, and sends automated WhatsApp/Email confirmations.',
    category: 'specialist',
    department: 'operations',
    autonomyLevel: 2,
    riskTier: 'LOW',
    version: '1.0.0',
    isSystem: true,
    config: {
      systemPrompt: 'You are the Xylarc Booking Specialist. You inspect slot availability, confirm participant timezones, reserve confirmed slots, and trigger instant confirmations.',
      tools: ['calendar_check_slots', 'calendar_book_slot', 'calendar_cancel_slot', 'whatsapp_send_message'],
      dataAccessScope: ['customer_profile', 'calendar_schedule', 'location_read'],
      modelPolicy: {
        primaryModel: 'gemini-2.5-flash',
        temperature: 0.1,
        maxTokens: 2048,
      },
      escalationRules: {
        triggers: ['slot_conflict_detected', 'special_vip_request'],
        escalationTarget: 'human',
        minConfidenceThreshold: 0.90,
      },
      limits: {
        maxConcurrentTasks: 20,
        maxCostPerExecutionUsd: 0.25,
        timeoutMs: 20000,
        maxDailyOutreachPerCustomer: 3,
      },
      verificationApproach: 'deterministic',
      owner: 'system',
    },
  },
  {
    slug: 'customer_support_specialist',
    name: 'Customer Support & Resolution Agent',
    description: 'Resolves inbound customer inquiries, retrieves order and ticket statuses, executes standard troubleshooting, and triages complex issues.',
    category: 'specialist',
    department: 'support',
    autonomyLevel: 2,
    riskTier: 'LOW',
    version: '1.0.0',
    isSystem: true,
    config: {
      systemPrompt: 'You are the Xylarc Customer Support Agent. You provide helpful, factual, and compliant answers to customer questions based strictly on verified business knowledge.',
      tools: ['knowledge_base_search', 'order_status_lookup', 'ticket_create', 'ticket_escalate'],
      dataAccessScope: ['customer_timeline', 'knowledge_base', 'order_history'],
      modelPolicy: {
        primaryModel: 'gemini-2.5-flash',
        temperature: 0.2,
        maxTokens: 4096,
      },
      escalationRules: {
        triggers: ['customer_anger_detected', 'refund_requested_above_limit', 'safety_complaint'],
        escalationTarget: 'human',
        minConfidenceThreshold: 0.80,
      },
      limits: {
        maxConcurrentTasks: 20,
        maxCostPerExecutionUsd: 0.35,
        timeoutMs: 30000,
        maxDailyOutreachPerCustomer: 3,
      },
      verificationApproach: 'deterministic',
      owner: 'system',
    },
  },
  {
    slug: 'quality_review_verifier',
    name: 'Quality & Policy Review Verifier',
    description: 'Independent verification agent that checks completed actions for hallucination, policy compliance, and factual accuracy before final delivery.',
    category: 'verifier',
    department: 'general',
    autonomyLevel: 1,
    riskTier: 'LOW',
    version: '1.0.0',
    isSystem: true,
    config: {
      systemPrompt: 'You are the Xylarc Quality & Policy Reviewer. You deterministically inspect agent claims against source facts, verifying evidence attribution and policy rules.',
      tools: ['policy_rule_checker', 'evidence_grounding_evaluator', 'pii_leakage_detector'],
      dataAccessScope: ['agent_execution_trace', 'source_documents', 'policy_definitions'],
      modelPolicy: {
        primaryModel: 'gemini-2.5-pro',
        temperature: 0.0,
        maxTokens: 4096,
      },
      escalationRules: {
        triggers: ['policy_violation_found', 'unsupported_hallucinated_fact'],
        escalationTarget: 'human',
        minConfidenceThreshold: 0.95,
      },
      limits: {
        maxConcurrentTasks: 30,
        maxCostPerExecutionUsd: 0.40,
        timeoutMs: 25000,
        maxDailyOutreachPerCustomer: 1,
      },
      verificationApproach: 'deterministic',
      owner: 'system',
    },
  },
];
